// Generated by CoffeeScript 1.6.3
var StylPlugin, styl;

styl = require('styl');

module.exports = StylPlugin = (function() {
  StylPlugin.prototype.brunchPlugin = true;

  function StylPlugin(config) {
    this.config = config;
    null;
  }

  StylPlugin.prototype.compile = function(data, path, callback) {
    var err, error, result;
    result = error = null;
    try {
      return result = styl(data, {
        whitespace: true
      }).toString();
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  return StylPlugin;

})();
